name: 'command testing action'
description: 'test command output, this action for developing actions'
author: 'MeilCli'
branding:
  icon: alert-circle
  color: blue
inputs:
  command:
    description: 'execute command'
    required: true
  expect_regex:
    description: 'expect command output, regex value'
  expect_contain:
    description: 'expect command output, include value'
runs:
  using: 'node12'
  main: 'dist/index.js'
