name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and test
      run: |
        npm install
        npm run build
      env:
        CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: MeilCli/test-command-action@master
        with:
          command: echo 'Hello World'
          expect: 'Hello\sWorld'
      - uses: MeilCli/test-command-action@master
        with:
          command: echo 'Hello World'
          expect: 'Hello\sTest'
      - run: echo previous faild
        if: failure()
